Repository hardingadonis/miu-shop, pull requests merged in 2023-12, with the labels that each got.

#55 Vương: Cart Page
  src/main/java/io/hardingadonis/miu/controller/web/CartServlet.java
  src/main/java/io/hardingadonis/miu/services/Hash.java
  src/main/webapp/assets/css/web/cart.css
  src/main/webapp/assets/js/web/cartHandler.js
  src/main/webapp/assets/js/web/common/commonHandler.js
  src/main/webapp/assets/js/web/productHandler.js
  src/main/webapp/view/web/cart.jsp
  src/main/webapp/view/web/common/_header.jsp
Labels: enhancement

#59 Vương: Change password page
  src/main/java/io/hardingadonis/miu/controller/web/ChangePasswordServlet.java
  src/main/webapp/assets/css/web/change-password.css
  src/main/webapp/assets/js/web/changePasswordHandler.js
  src/main/webapp/view/web/change-password.jsp
  src/main/webapp/view/web/login.jsp
Labels: enhancement

#58 Remove 4.5 star in product page
  src/main/webapp/view/web/product.jsp
Labels: bug

#64 Vuong delivery address page
  src/main/java/io/hardingadonis/miu/controller/web/AddAdressServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/DeliveryAddressServlet.java
  src/main/webapp/assets/css/web/add-address.css
  src/main/webapp/assets/css/web/delivery-address.css
  src/main/webapp/assets/js/web/addAddressHandler.js
  src/main/webapp/view/web/add-address.jsp
  src/main/webapp/view/web/cart.jsp
  src/main/webapp/view/web/delivery-address.jsp
Labels: enhancement

#67 Thuy show and hide password (bonus eye)
  src/main/webapp/assets/css/web/login.css
  src/main/webapp/assets/css/web/register.css
  src/main/webapp/assets/js/web/loginHandler.js
  src/main/webapp/assets/js/web/registerHandler.js
  src/main/webapp/view/web/login.jsp
  src/main/webapp/view/web/register.jsp
Labels: documentation

#68 Vương: Checkout page
  database/setup.sql
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutServlet.java
  src/main/java/io/hardingadonis/miu/dao/OrderDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/CategoryDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/OrderDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/webapp/assets/js/web/checkoutHandler.js
  src/main/webapp/view/web/checkout.jsp
  src/main/webapp/view/web/product.jsp
Labels: enhancement

#70 Vương: Update checkout page
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutSuccessServlet.java
  src/main/java/io/hardingadonis/miu/dao/CartDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/CartDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/services/Singleton.java
  src/main/java/io/hardingadonis/miu/services/vnpay/VNPayConfig.java
  src/main/webapp/view/web/cart.jsp
  src/main/webapp/view/web/checkout-success.jsp
  src/main/webapp/view/web/checkout.jsp
Labels: enhancement

#71 Handling the cart when checkout with vnpay fail
  src/main/webapp/view/web/checkout-success.jsp
Labels: bug

#72 Handle the checkout page when user has no deilivery address
  src/main/webapp/view/web/add-address.jsp
  src/main/webapp/view/web/change-password.jsp
  src/main/webapp/view/web/checkout.jsp
  src/main/webapp/view/web/profile.jsp
Labels: bug

#74 Vương: Purchase history page
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutStatusServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/PurchaseHistoryDetailServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/PurchaseHistoryServlet.java
  src/main/java/io/hardingadonis/miu/dao/OrderDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/OrderDAOMySQLImpl.java
  src/main/webapp/assets/css/web/purchase-history-detail.css
  src/main/webapp/assets/css/web/purchase-history.css
  src/main/webapp/assets/js/web/purchaseHistoryHandler.js
  src/main/webapp/view/web/change-password.jsp
  src/main/webapp/view/web/checkout-status.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/delivery-address.jsp
  src/main/webapp/view/web/profile.jsp
  src/main/webapp/view/web/purchase-history-detail.jsp
  src/main/webapp/view/web/purchase-history.jsp
Labels: enhancement

#75 Hotfix all bugs
  src/main/java/io/hardingadonis/miu/controller/web/PurchaseHistoryServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
  src/main/java/io/hardingadonis/miu/services/Server.java
  src/main/java/io/hardingadonis/miu/services/vnpay/VNPayConfig.java
  src/main/webapp/view/web/checkout-status.jsp
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/purchase-history-detail.jsp
Labels: bug, enhancement

#77 Vương: Forgot password functionally
  src/main/java/io/hardingadonis/miu/controller/web/ForgotChangePasswordServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/ForgotPasswordServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/VerifyServlet.java
  src/main/java/io/hardingadonis/miu/services/Email.java
  src/main/java/io/hardingadonis/miu/services/impl/gmail/EmailGmailImpl.java
  src/main/webapp/assets/css/web/forgot-change-password.css
  src/main/webapp/assets/css/web/forgot-password.css
  src/main/webapp/assets/js/web/forgotChangePasswordHandler.js
  src/main/webapp/assets/js/web/forgotPasswordHandler.js
  src/main/webapp/view/web/forgot-change-password.jsp
  src/main/webapp/view/web/forgot-password.jsp
  src/main/webapp/view/web/login.jsp
Labels: enhancement

#82 Fix bug
  src/main/java/io/hardingadonis/miu/controller/web/CheckoutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
Labels: bug

#83 Responsive
  src/main/webapp/assets/css/web/common/common.css
  src/main/webapp/view/web/add-address.jsp
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/product.jsp
  src/main/webapp/view/web/search.jsp
Labels: enhancement

#86 Hoang admin dashboard
  src/main/java/io/hardingadonis/miu/controller/admin/OrderAdmin.java
  src/main/java/io/hardingadonis/miu/model/Order.java
  src/main/webapp/assets/js/admin/edit-category.js
  src/main/webapp/assets/js/admin/order-admin.js
  src/main/webapp/view/admin/category-admin.jsp
  src/main/webapp/view/admin/dashboard-admin.jsp
  src/main/webapp/view/admin/order-admin.jsp
  src/main/webapp/view/admin/user-admin.jsp
Labels: enhancement
