Repository hardingadonis/miu-shop, pull requests merged in 2023-11, with the labels that each got.

#1 Vương: Setup Docker
  database/Dockerfile
  docker-compose.yml
  server/Dockerfile
Labels: documentation, enhancement, good first issue

#2 Vương: Setup CI/CD
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  database/Dockerfile
  docker-compose.yml
  get_version.sh
  pom.xml
  server/Dockerfile
Labels: documentation, enhancement, good first issue

#3 Hoàng: Coding model
  src/main/java/io/hardingadonis/miu/model/Admin.java
  src/main/java/io/hardingadonis/miu/model/Cart.java
  src/main/java/io/hardingadonis/miu/model/Category.java
  src/main/java/io/hardingadonis/miu/model/Order.java
  src/main/java/io/hardingadonis/miu/model/OrderData.java
  src/main/java/io/hardingadonis/miu/model/Product.java
  src/main/java/io/hardingadonis/miu/model/User.java
Labels: documentation, enhancement, good first issue

#5 Vương: Setup repository
  .github/FUNDING.yml
  README.md
Labels: documentation

#6 Vương: Coding model detail
  src/main/java/io/hardingadonis/miu/model/Admin.java
  src/main/java/io/hardingadonis/miu/model/Cart.java
  src/main/java/io/hardingadonis/miu/model/Category.java
  src/main/java/io/hardingadonis/miu/model/Order.java
  src/main/java/io/hardingadonis/miu/model/OrderData.java
  src/main/java/io/hardingadonis/miu/model/Product.java
  src/main/java/io/hardingadonis/miu/model/User.java
  src/main/java/io/hardingadonis/miu/model/detail/AdminRole.java
  src/main/java/io/hardingadonis/miu/model/detail/OrderStatus.java
  src/main/java/io/hardingadonis/miu/model/detail/Payment.java
  src/main/java/io/hardingadonis/miu/model/detail/UserAddress.java
  src/main/java/io/hardingadonis/miu/model/detail/UserGender.java
  src/main/java/io/hardingadonis/miu/model/detail/UserStatus.java
Labels: documentation, enhancement, good first issue

#7 Vương: Add services
  pom.xml
  src/main/java/io/hardingadonis/miu/services/Converter.java
  src/main/java/io/hardingadonis/miu/services/DBContext.java
  src/main/java/io/hardingadonis/miu/services/Email.java
  src/main/java/io/hardingadonis/miu/services/Hash.java
  src/main/java/io/hardingadonis/miu/services/Singleton.java
  src/main/java/io/hardingadonis/miu/services/impl/gmail/EmailGmailImpl.java
  src/main/java/io/hardingadonis/miu/services/impl/mysql/DBContextMySQLImpl.java
  src/main/resources/config.gmail.properties
  src/main/resources/config.mysql.properties
Labels: documentation, help wanted, good first issue

#10 Vương: Writing DAO Parttern for all models
  pom.xml
  src/main/java/io/hardingadonis/miu/dao/AdminDAO.java
  src/main/java/io/hardingadonis/miu/dao/CartDAO.java
  src/main/java/io/hardingadonis/miu/dao/CategoryDAO.java
  src/main/java/io/hardingadonis/miu/dao/OrderDAO.java
  src/main/java/io/hardingadonis/miu/dao/OrderDataDAO.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/UserDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/AdminDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/CartDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/CategoryDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/OrderDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/OrderDataDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/UserDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/model/Product.java
  src/main/java/io/hardingadonis/miu/services/Singleton.java
Labels: documentation, enhancement, good first issue

#12 Vương: Coding homepage for Miu Shop
  README.md
  pom.xml
  src/main/java/io/hardingadonis/miu/controller/web/HomeServlet.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/filter/web/DefaultFilter.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/css/style.css
  src/main/webapp/assets/images/banners/08311df62a11bc7250b5f76d679a5831da62b7ef050f0b9ffbea60abc0369806.jpg
  src/main/webapp/assets/images/banners/296dc69cb2e3bc78ec76fb1f4a84a1dbb8ffd92300d6d3746a32272e38f7e8e7.jpg
  src/main/webapp/assets/images/banners/384db07758f20287b1a53cdeaf079b207cd4ca4adc64fc8330aae19b6cb4754c.jpg
  src/main/webapp/assets/images/banners/6367b4f9a204df6f7f4ca3dd36c7b6fce1f51101e8bc9f59356a19301d84f625.jpg
  src/main/webapp/assets/images/favicon/favicon.png
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
Labels: documentation, help wanted, good first issue

#15 Update Release Actions
  .github/workflows/release.yml
Labels: bug, good first issue

#17 Vương: Users login functionality
  src/main/java/io/hardingadonis/miu/controller/web/LoginServlet.java
  src/main/java/io/hardingadonis/miu/dao/AdminDAO.java
  src/main/java/io/hardingadonis/miu/dao/CategoryDAO.java
  src/main/java/io/hardingadonis/miu/dao/OrderDAO.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/UserDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/AdminDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/CategoryDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/OrderDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/UserDAOMySQLImpl.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/css/common.css
  src/main/webapp/assets/css/login.css
  src/main/webapp/assets/images/covers/d8c447f52ed8adc4ec394b0d1a0b7cda88dc9c90b6e3795796c90dd27267214b.jpg
  src/main/webapp/assets/js/emailValidation.js
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/login.jsp
Labels: documentation, enhancement, good first issue

#18 Fix avatars path in ``user`` table
  database/setup.sql
Labels: bug

#19 Vương: Users logout functionality
  src/main/java/io/hardingadonis/miu/controller/web/LogoutServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/view/web/common/_header.jsp
Labels: documentation, enhancement, good first issue

#23 Redirect to ``home`` when click
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/common/_header.jsp
Labels: enhancement

#26 Vương: Update homepage
  src/main/webapp/assets/css/common.css
  src/main/webapp/assets/css/home.css
  src/main/webapp/assets/js/homeHandler.js
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/home.jsp
Labels: bug, documentation, enhancement

#25 Vương: Product Detail Page
  src/main/java/io/hardingadonis/miu/controller/web/ProductDetailServlet.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/css/web/product.css
  src/main/webapp/assets/js/productHandler.js
  src/main/webapp/view/web/product.jsp
Labels: documentation, enhancement

#28 Vương: Resstruct source code
  src/main/java/io/hardingadonis/miu/controller/web/HomeServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/LoginServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/LogoutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/ProductDetailServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/css/web/common.css
  src/main/webapp/assets/css/web/home.css
  src/main/webapp/assets/css/web/login.css
  src/main/webapp/assets/css/web/product.css
  src/main/webapp/assets/js/web/homeHandler.js
  src/main/webapp/assets/js/web/loginHandler.js
  src/main/webapp/assets/js/web/productHandler.js
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/login.jsp
  src/main/webapp/view/web/product.jsp
Labels: documentation, enhancement

#29 Vương: About Page
  src/main/java/io/hardingadonis/miu/controller/web/AboutServlet.java
  src/main/webapp/assets/images/covers/55a08ee47df7b628ad07def611869c29dfba92dba3c803a5ff70dd88608817ca.avif
  src/main/webapp/view/web/about.jsp
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
Labels: documentation, enhancement

#31 Update ``Publish Miu Shop Images`` actions
  .github/workflows/publish.yml
Labels: documentation, enhancement, good first issue

#33 Update docker compose
  docker-compose.yml
Labels: documentation

#35 Vương: Search Functionally
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/webapp/assets/css/web/search.css
  src/main/webapp/assets/js/web/searchHandler.js
  src/main/webapp/view/web/common/_footer.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/search.jsp
Labels: documentation, enhancement

#36 Fix category path in product detail page
  src/main/webapp/view/web/product.jsp
Labels: bug

#38 Update Register Form
  src/main/java/io/hardingadonis/miu/controller/web/LoginServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/RegisterServlet.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/UserDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/services/impl/gmail/EmailGmailImpl.java
  src/main/webapp/assets/css/web/register.css
  src/main/webapp/assets/images/avatars/female.webp
  src/main/webapp/assets/images/avatars/male.webp
  src/main/webapp/assets/js/web/registerHandler.js
  src/main/webapp/view/web/login.jsp
  src/main/webapp/view/web/register.jsp
Labels: bug, duplicate, enhancement

#32 Hoang register form
  src/main/java/io/hardingadonis/miu/controller/web/LoginServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/RegisterServlet.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/UserDAOMySQLImpl.java
  src/main/java/io/hardingadonis/miu/services/impl/gmail/EmailGmailImpl.java
  src/main/webapp/assets/css/web/register.css
  src/main/webapp/assets/images/avatars/female.webp
  src/main/webapp/assets/images/avatars/male.webp
  src/main/webapp/assets/js/web/registerHandler.js
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/login.jsp
  src/main/webapp/view/web/register.jsp
Labels: documentation, enhancement

#39 Vương: Fix search
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
  src/main/java/io/hardingadonis/miu/dao/ProductDAO.java
  src/main/java/io/hardingadonis/miu/dao/impl/mysql/ProductDAOMySQLImpl.java
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/search.jsp
Labels: bug, enhancement

#40 Vương: Error handling
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/view/error/404.jsp
  src/main/webapp/view/error/500.jsp
Labels: enhancement

#41 Hotfix Docker
  database/Dockerfile
  server/Dockerfile
Labels: bug

#42 Update actions
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: enhancement

#45 Update servlet name
  src/main/java/io/hardingadonis/miu/controller/web/AboutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/HomeServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/LoginServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/LogoutServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/ProductDetailServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/RegisterServlet.java
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
Labels: duplicate

#48 Fix size 4 pictures
  src/main/webapp/assets/images/products/11bc1d209ebd5365a5f2633f0f9abfc7f72709f72c826dab26e39ca13d6ebac6.webp
  src/main/webapp/assets/images/products/2f83e9597e3cc68fa309c12bfc076b192188d48b70221e1f4accd69027118a6b.webp
  src/main/webapp/assets/images/products/5da05c6eaad9373347158ca31759fbf256bddcd3c232cda39370357c4bb0d56c.webp
  src/main/webapp/assets/images/products/a2cb1542ecd069be88f5cfce91368b3e213a5ad4eee7fb8a2ca16f3b7bb101a3.webp
  src/main/webapp/assets/images/products/d7ad87be32601887de5ab51d32a3a8156c9700c854ab4b646fa88c0c9d9b9eb0.webp
Labels: bug

#50 Vương: Add products to the cart functionality
  src/main/webapp/assets/js/web/common/commonHandler.js
  src/main/webapp/assets/js/web/homeHandler.js
  src/main/webapp/assets/js/web/productHandler.js
  src/main/webapp/assets/js/web/searchHandler.js
  src/main/webapp/view/web/about.jsp
  src/main/webapp/view/web/common/_header.jsp
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/product.jsp
  src/main/webapp/view/web/search.jsp
Labels: enhancement

#53 Vương: Fix product cart
  src/main/webapp/assets/css/web/home.css
  src/main/webapp/assets/css/web/product.css
  src/main/webapp/assets/css/web/search.css
  src/main/webapp/assets/js/web/homeHandler.js
  src/main/webapp/assets/js/web/productHandler.js
  src/main/webapp/assets/js/web/searchHandler.js
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/product.jsp
  src/main/webapp/view/web/search.jsp
Labels: bug

#51 Vương: Fix pagination in search page.
  src/main/java/io/hardingadonis/miu/controller/web/SearchServlet.java
  src/main/webapp/assets/css/web/search.css
  src/main/webapp/assets/js/web/homeHandler.js
  src/main/webapp/assets/js/web/productHandler.js
  src/main/webapp/assets/js/web/searchHandler.js
  src/main/webapp/view/web/home.jsp
  src/main/webapp/view/web/product.jsp
  src/main/webapp/view/web/search.jsp
Labels: enhancement
